apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: opentrek
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: tegola-volume
      mountPath: /data
  volumes:
  - name: tegola-volume
    persistentVolumeClaim:
      claimName: tegola-pvc